site_name: SmartPal Instructor Guide
site_url: https://www.smartpal.org/
theme:
  name: material
  custom_dir: docs/css  
  features:
    # - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  favicon: images/favicon.png
  # logo: images/logo-with-text-long-300.jpg
extra_css:
  - css/extra.css
extra_javascript:
  - js/redirects.js

plugins:
  # - social
  - search

nav:
  - Overview: index.md
  - How It Works: how-it-works.md
  - Deployment Options: ways-to-use.md
  - Instructional Tool Mode: instructional-tool.md
  - Research Participation Mode: research-participation.md
  - Academic Integrity: academic-integrity.md
  - Roles & Responsibilities: responsibilities.md
  - Privacy: privacy.md
  # - Canvas Checklist: canvas-checklist.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list


copyright: |
  &copy; 2025 SmartPAL AI Inc.